---
- name: make log dir
  file: path=/var/log/nginx owner=root group=root state=directory

- name: make etc folder
  file: path=/data/nginx owner=root group=root state=directory

- name: pull container
  command: docker pull {{docker_repo}}/nginx:latest

- name: remove container
  command: docker rm -f nginx
  ignore_errors: yes

- name: start container
  command: docker run -d --restart=always --name nginx -v /data/nginx/auth:/etc/nginx/auth -v /var/log/nginx/log:/var/log/nginx -v /tmp/capasa:/tmp/capasa -v /data/nginx/conf.d:/etc/nginx/conf.d -p 80:80 -p 443:433 {{docker_repo}}/nginx

- name: restart nginx
  command: docker restart nginx
